# Generated by Django 5.2 on 2025-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accepted_cmp1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accepted_cmp2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accepted_cmp3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accepted_cmp4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accepted_cmp5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complain',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_fish_products',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_fruits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_gold_prods',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_meat_products',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_sweet_products',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mnt_wines',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='response',
            field=models.IntegerField(),
        ),
    ]
