# Generated by Django 5.2 on 2025-04-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPA_APP', '0002_alter_customer_accepted_cmp1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
