# Generated by Django 5.2 on 2025-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPA_APP', '0003_customer_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cluster_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
