# Generated by Django 5.2 on 2025-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPA_APP', '0004_customer_cluster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(unique=True)),
                ('cluster_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cluster_name',
        ),
    ]
