# Generated by Django 5.2 on 2025-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPA_APP', '0006_alter_customer_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shihoutte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
